Fix compilation error within gcagent due to API change
.. github.com/couchbase/query/datastore/couchbase/gcagent
datastore/couchbase/gcagent/txagent.go:342:6: cannot use txnMeta (type transactions.MutableItemMeta) as type *transactions.MutableItemMeta in field value
datastore/couchbase/gcagent/txagent.go:356:6: cannot use txnMeta (type transactions.MutableItemMeta) as type *transactions.MutableItemMeta in field value

+ API was updated by this change within couchbaselabs/gocbcore-transactions ..
    https://github.com/couchbaselabs/gocbcore-transactions/commit/036ce56a676f86684e9b28c5f3783e58a0c5777c

Change-Id: Ia96fdc07b89f0e5122923ce6f03ab7cadfe4ab01
Reviewed-on: http://review.couchbase.org/c/query/+/139045
Reviewed-by: Sitaram Vemulapalli <sitaram.vemulapalli@couchbase.com>
Tested-by: Sitaram Vemulapalli <sitaram.vemulapalli@couchbase.com>