Commit parser/n1ql/y.go into couchbase/query
+ For go modules to work .. golang's recommendation
  is to commit all generated files.
+ FTS is introducing go modules support across all
  its projects. When go.mod is added to couchbase/n1fty,
  it complains the following ..

github.com/couchbase/query/parser/n1ql
../../../../pkg/mod/github.com/couchbase/query@v0.0.0-20200417195246-d8e3f47d25b2/parser/n1ql/n1ql.go:110:19: undefined: yySymType

+ The fix here would be to commit parser/n1ql/y.go where
  the type yySymType is defined.
+ Note that everytime somebody changes y.go, they should
  merge it in, so with go modules we continue to pick
  up the latest definition/version.

Change-Id: I324dec12ad0c12201f41da99cc52e544840d667a
Reviewed-on: http://review.couchbase.org/c/query/+/126063
Reviewed-by: Marco Greco <marco.greco@couchbase.com>
Reviewed-by: Sitaram Vemulapalli <sitaram.vemulapalli@couchbase.com>
Reviewed-by: Abhinav Dangeti <abhinav@couchbase.com>
Tested-by: Sitaram Vemulapalli <sitaram.vemulapalli@couchbase.com>